[Icon Theme]
Name=Yulo
Comment=Yulo sakura-pink icon theme
Inherits=Adwaita,Yaru,hicolor
Example=folder

# Directory definitions
[scalable/apps]
Size=48
Context=Apps
Type=Scalable

[scalable/places]
Size=48
Context=Places
Type=Scalable

[scalable/mimetypes]
Size=48
Context=MimeTypes
Type=Scalable

[scalable/status]
Size=48
Context=Status
Type=Scalable

[scalable/actions]
Size=48
Context=Actions
Type=Scalable

[48x48/apps]
Size=48
Context=Apps
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[32x32/apps]
Size=32
Context=Apps
Type=Fixed

[24x24/apps]
Size=24
Context=Apps
Type=Fixed

[16x16/apps]
Size=16
Context=Apps
Type=Fixed
